repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.7
    hooks:
      - id: ruff-check
        name: "ruff fix"
        args: [--fix]
      - id: ruff-format
        name: "ruff format"
