INHERIT: ../../mkdocs.base.yml

site_name: my-sample-package-provider-app

docs_dir: docs/
site_dir: ../../site/packages/my-sample-package-provider-app/

nav:
  - Overview: index.md
  - API Reference: api/reference.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_source: true
            show_root_heading: true
            members_order: source
